### ISSUE TITLE
Choose Non-RESTful search endpoint

### ISSUE THREAD

**Issue by dcardona23** [Crosswolfv1/Little_Shop#18]

**Comment by Crosswolfv1** [comment]
A. One Merchant & All Items:

 > Find one MERCHANT based on search criteria, and
 > Find all ITEMS based on search criteria

Or,

B. One Item & All Merchants:

> Find one ITEM based on search criteria, and
> Find all MERCHANTS based on search criteria

Once you choose the group you are implementing, you will build the corresponding endpoints which will **NOT** follow RESTful convention. For example:

> GET /api/vi/items/find, find a single item which matches a search term
> GET /api/vi/items/find_all, find all items which match a search term
> GET /api/vi/merchants/find, find a single merchant which matches a search term
> GET /api/vi/merchants/find_all, find all merchants which match a search term

**Comment by dcardona23** [comment]
Chose A. One merchant and all items
